# Generated by Django 3.2.25 on 2024-11-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zena', '0005_new_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='news_images/'),
        ),
    ]
